version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # Load all variables from .env
    volumes:
      - ./src/logs:/app/src/logs
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80" # Map host port 8000 to nginx's default port 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
